name: Anglar CI

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Descargar Repositorio
              uses: actions/checkout@v4
            
            - name: Configurar/Instalar Node.js
              uses: actions/setup-node@v4
              with:
                    node-version: 20
                    
            - name: Instalar Dependencias
              run: npm install
        
            - name: Ejecutar Pruebas
              run: npm test --run
            
            - name: Generar Build
              run: npm run build